export const SKILLS_CATEGORIES = {
  systemsNetworks: ["Linux", "Windows", "Virtualisation", "Docker", "Routage", "VLAN", "Wireshark", "Marionnet", "Programmation système", "SSH", "iptables", "WebSocket"],
  databases: ["MySQL", "PostgreSQL", "SQL", "SQLite", "Modélisation", "UML", "Requêtes", "Exploitation BDD"],
  development: [
    "Java",
    "PHP",
    "JavaScript",
    "TypeScript",
    "C",
    "C++",
    "Python",
    "Node.js",
    "Express",
    "Socket.io",
    "Phaser 3",
    "POO",
    "MVC",
    "IHM",
    "API REST",
    "Android",
    "Architecture logicielle",
    "Playwright",
  ],
  qualitiesProjects: ["Gestion de projet", "Communication", "Travail d'équipe", "PPP", "Droit du numérique"],
  cybersecurity: ["Cryptographie", "Sécurité réseau", "Sécurité système", "Pare-feu", "Bonnes pratiques"],
} as const;

